// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

#define SRS_AUTO_BUILD_TS "1398668018"
#define SRS_AUTO_BUILD_DATE "2014-04-28 14:53:38"
#define SRS_AUTO_UNAME "Linux dev6 2.6.32-71.el6.x86_64 #1 SMP Fri May 20 03:51:51 BST 2011 x86_64 x86_64 x86_64 GNU/Linux"
#define SRS_AUTO_USER_CONFIGURE " --disable-all --with-librtmp"
#define SRS_AUTO_CONFIGURE "--prefix=/usr/local/srs --without-hls --without-dvr --without-nginx --without-ssl --without-ffmpeg --without-transcode --without-ingest --without-http-callback --without-http-server --without-http-api --with-librtmp --without-bwtc --without-research --without-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12"

#define SRS_AUTO_ARM_TOOL_CHAIN "cc=arm-linux-gnueabi-gcc gcc=arm-linux-gnueabi-gcc g++=arm-linux-gnueabi-g++ ar=arm-linux-gnueabi-ar ld=arm-linux-gnueabi-ld randlib=arm-linux-gnueabi-ranlib"

#undef SRS_AUTO_HTTP_PARSER
#undef SRS_AUTO_HTTP_SERVER
#undef SRS_AUTO_HTTP_API
#undef SRS_AUTO_NGINX
#undef SRS_AUTO_DVR
#undef SRS_AUTO_HLS
#undef SRS_AUTO_HTTP_CALLBACK
#undef SRS_AUTO_SSL
#undef SRS_AUTO_FFMPEG
#undef SRS_AUTO_TRANSCODE
#undef SRS_AUTO_INGEST
#undef SRS_AUTO_GPERF
#undef SRS_AUTO_GPERF_MC
#undef SRS_AUTO_GPERF_MP
#undef SRS_AUTO_GPERF_CP
#undef SRS_AUTO_ARM_UBUNTU12

#define SRS_AUTO_PREFIX "/usr/local/srs"

#define SRS_AUTO_CONSTRIBUTORS "\
winlin<winlin@vip.126.com> \
wenjie.zhao<740936897@qq.com> \
xiangcheng.liu<liuxc0116@foxmail.com> \
naijia.liu<youngcow@youngcow.net> \
alcoholyi<alcoholyi@qq.com> \
byteman<wangchen2011@gmail.com> \
chad.wang<chad.wang.cn@gmail.com> \
"

// for win32, time() for srs_protocol_rtmp.cpp
#include <time.h>

#endif

